# Generated by Django 3.1.7 on 2021-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('WA', 'Waiting Approval'), ('A', 'Approved'), ('C', 'Canceled'), ('F', 'Finished')], default='WA', max_length=2),
        ),
    ]
